### ISSUE TITLE
@Override 错误 RN版本0.47 使用的组件版本 1.0.0

### ISSUE THREAD

**Issue by guopeng1994** [qiepeipei/react-native-clear-cache#1]
react-native-clear-cache\android\src\main\java\com\example\qiepeipei\react_native_clear_cache\ClearCachePackage.java:28: 错误: 方法不会覆盖或实现超类型的
方法
    @Override
    ^
1 个错误

望早日修复

**Comment by qiepeipei** [comment]
已更新
